site_name: FastApi-pet

nav:
  - About: index.md
  - Examples: examples.md

theme:
  name: material
  features:
    - navigation.tabs
    - search.suggestions
    - search.highlight
    - content.code.copy
    -