name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        # https://github.com/actions/checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        # The actions/checkout action in GitHub Actions is used to download or "checkout" the code from a repository
        # into the workflow runner. This is a fundamental step in most GitHub Actions workflows, as it makes the
        # repository's files available for subsequent steps, such as building, testing, or deploying the code.
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        # This action will create and boot a builder that can be used in the following steps
        # of your workflow if you're using Buildx or the build-push action.
        # https://github.com/docker/setup-buildx-action
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        # https://github.com/docker/build-push-action/pkgs/container/build-push-action
        # GitHub Action to build and push Docker images
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          platforms: |
            linux/amd64,
            linux/arm64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/shop-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/shop-api:${{ github.sha }}